local PLUGIN = PLUGIN;

-- MPF voices. Remove everything up to the next comment to remove all MPF voices.
Schema.voices:Add("Combine", "Judgement", "Suspect prepare to receive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav");
Schema.voices:Add("Combine", "Priority Two", "I have a priority two anti-citizen here.", "npc/metropolice/vo/priority2anticitizenhere.wav");
Schema.voices:Add("Combine", "Prosecute", "Prosecute!", "npc/metropolice/vo/prosecute.wav");
Schema.voices:Add("Combine", "Amputate Ready", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav");
Schema.voices:Add("Combine", "Rodger That", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav");
Schema.voices:Add("Combine", "Sweeping", "Sweeping for suspect.", "npc/metropolice/hiding02.wav");
Schema.voices:Add("Combine", "Isolate", "Isolate!", "npc/metropolice/hiding05.wav");
Schema.voices:Add("Combine", "You Can Go", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav");
Schema.voices:Add("Combine", "Need Assistance", "Eleven-ninety-nine, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav");
Schema.voices:Add("Combine", "Administer", "Administer.", "npc/metropolice/vo/administer.wav");
Schema.voices:Add("Combine", "Affirmative", "Affirmative.", "npc/metropolice/vo/affirmative.wav");
Schema.voices:Add("Combine", "All Units Move In", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav");
Schema.voices:Add("Combine", "Amputate", "Amputate.", "npc/metropolice/vo/amputate.wav");
Schema.voices:Add("Combine", "Suspect One", "I got suspect one here.", "npc/metropolice/vo/gotsuspect1here.wav");
Schema.voices:Add("Combine", "Help", "Help!", "npc/metropolice/vo/help.wav");
Schema.voices:Add("Combine", "Running", "He's running!", "npc/metropolice/vo/hesrunning.wav");
Schema.voices:Add("Combine", "Hold It", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav");
Schema.voices:Add("Combine", "Move Along 2", "I said move along.", "npc/metropolice/vo/isaidmovealong.wav");
Schema.voices:Add("Combine", "Malcompliance", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav");
Schema.voices:Add("Combine", "Keep Moving", "Keep moving!", "npc/metropolice/vo/keepmoving.wav");
Schema.voices:Add("Combine", "Lock Position", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav");
Schema.voices:Add("Combine", "Trouble", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav");
Schema.voices:Add("Combine", "Look Out", "Look out!", "npc/metropolice/vo/lookout.wav");
Schema.voices:Add("Combine", "Minor Hits", "Minor hits, continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav");
Schema.voices:Add("Combine", "Move", "Move!", "npc/metropolice/vo/move.wav");
Schema.voices:Add("Combine", "Move Along", "Move along!", "npc/metropolice/vo/movealong3.wav");
Schema.voices:Add("Combine", "Move Back", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav");
Schema.voices:Add("Combine", "Move It", "Move it!", "npc/metropolice/vo/moveit2.wav");
Schema.voices:Add("Combine", "Hardpoint", "Moving to hardpoint.", "npc/metropolice/vo/movingtohardpoint.wav");
Schema.voices:Add("Combine", "Officer Help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav");
Schema.voices:Add("Combine", "Privacy", "Possible level three civil privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav");
Schema.voices:Add("Combine", "Anti-Citizen", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav");
Schema.voices:Add("Combine", "Citizen", "Citizen.", "npc/metropolice/vo/citizen.wav");
Schema.voices:Add("Combine", "Copy", "Copy.", "npc/metropolice/vo/copy.wav");
Schema.voices:Add("Combine", "Cover Me", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav");
Schema.voices:Add("Combine", "Assist Trespass", "Assist for a criminal trespass!", "npc/metropolice/vo/criminaltrespass63.wav");
Schema.voices:Add("Combine", "Destroy Cover", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav");
Schema.voices:Add("Combine", "Dont Move", "Don't move!", "npc/metropolice/vo/dontmove.wav");
Schema.voices:Add("Combine", "Final Verdict", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav");
Schema.voices:Add("Combine", "Final Warning", "Final warning!", "npc/metropolice/vo/finalwarning.wav");
Schema.voices:Add("Combine", "First Warning", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav");
Schema.voices:Add("Combine", "Get Down", "Get down!", "npc/metropolice/vo/getdown.wav");
Schema.voices:Add("Combine", "Get Out", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav");
Schema.voices:Add("Combine", "Search", "Search!", "npc/metropolice/vo/search.wav");
Schema.voices:Add("Combine", "Shit", "Shit!", "npc/metropolice/vo/shit.wav");
Schema.voices:Add("Combine", "Sentence Delivered", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav");
Schema.voices:Add("Combine", "Sterilize", "Sterilize!", "npc/metropolice/vo/sterilize.wav");
Schema.voices:Add("Combine", "Take Cover", "Take cover!", "npc/metropolice/vo/takecover.wav");
Schema.voices:Add("Combine", "Restrict", "Restrict!", "npc/metropolice/vo/restrict.wav");
Schema.voices:Add("Combine", "Restricted", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav");
Schema.voices:Add("Combine", "Second Warning", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav");
Schema.voices:Add("Combine", "Verdict", "You want a non-compliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav");
Schema.voices:Add("Combine", "Backup", "Backup!", "npc/metropolice/vo/backup.wav");
Schema.voices:Add("Combine", "Apply", "Apply.", "npc/metropolice/vo/apply.wav");
Schema.voices:Add("Combine", "Restriction", "Terminal restriction zone.", "npc/metropolice/vo/terminalrestrictionzone.wav");
Schema.voices:Add("Combine", "Complete", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav");
Schema.voices:Add("Combine", "Location Unknown", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav");
Schema.voices:Add("Combine", "Wrap It", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav");
Schema.voices:Add("Combine", "Now Get Out", "Now get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav");
Schema.voices:Add("Combine", "Haha", "Haha.", "npc/metropolice/vo/chuckle.wav");
Schema.voices:Add("Combine", "X-Ray", "X-Ray!", "npc/metropolice/vo/xray.wav");
Schema.voices:Add("Combine", "Patrol", "Patrol!", "npc/metropolice/vo/patrol.wav");
Schema.voices:Add("Combine", "Serve", "Serve.", "npc/metropolice/vo/serve.wav");
Schema.voices:Add("Combine", "Knocked Over", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav");
Schema.voices:Add("Combine", "Watch It", "Watch it!", "npc/metropolice/vo/watchit.wav");
Schema.voices:Add("Combine", "Restricted Canals", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav");
Schema.voices:Add("Combine", "505", "Subject is five-oh-five!", "npc/metropolice/vo/subjectis505.wav");
Schema.voices:Add("Combine", "404", "Possible 404 here!", "npc/metropolice/vo/possible404here.wav");
Schema.voices:Add("Combine", "Vacate", "Vacate citizen!", "npc/metropolice/vo/vacatecitizen.wav");
Schema.voices:Add("Combine", "Escapee", "Priority two escapee.", "npc/combine_soldier/vo/prioritytwoescapee.wav");
Schema.voices:Add("Combine", "Objective", "Priority one objective.", "npc/combine_soldier/vo/priority1objective.wav");
Schema.voices:Add("Combine", "Payback", "Payback.", "npc/combine_soldier/vo/payback.wav");
Schema.voices:Add("Combine", "Got Him Now", "Affirmative, we got him now.", "npc/combine_soldier/vo/affirmativewegothimnow.wav");
Schema.voices:Add("Combine", "Antiseptic", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav");
Schema.voices:Add("Combine", "Cleaned", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav");
Schema.voices:Add("Combine", "Cleanup", "Engaged in cleanup.", "npc/combine_soldier/vo/engagedincleanup.wav");
Schema.voices:Add("Combine", "Engaging", "Engaging.", "npc/combine_soldier/vo/engaging.wav");
Schema.voices:Add("Combine", "Full Response", "Executing full response.", "npc/combine_soldier/vo/executingfullresponse.wav");
Schema.voices:Add("Combine", "Heavy Resistance", "Overwatch advise, we have heavy resistance.", "npc/combine_soldier/vo/heavyresistance.wav");
Schema.voices:Add("Combine", "Inbound", "Inbound.", "npc/combine_soldier/vo/inbound.wav");
Schema.voices:Add("Combine", "Lost Contact", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav");
Schema.voices:Add("Combine", "Move In", "Move in!", "npc/combine_soldier/vo/movein.wav");
Schema.voices:Add("Combine", "Harden Position", "Harden that position!", "npc/combine_soldier/vo/hardenthatposition.wav");
Schema.voices:Add("Combine", "Go Sharp", "Go sharp, go sharp!", "npc/combine_soldier/vo/gosharpgosharp.wav");
Schema.voices:Add("Combine", "Delivered", "Delivered.", "npc/combine_soldier/vo/delivered.wav");
Schema.voices:Add("Combine", "Necrotics Inbound", "Necrotics, inbound!", "npc/combine_soldier/vo/necroticsinbound.wav");
Schema.voices:Add("Combine", "Necrotics", "Necrotics.", "npc/combine_soldier/vo/necrotics.wav");
Schema.voices:Add("Combine", "Outbreak", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav");
Schema.voices:Add("Combine", "Copy That", "Copy that.", "npc/combine_soldier/vo/copythat.wav");
Schema.voices:Add("Combine", "Outbreak Status", "Outbreak status is code.", "npc/combine_soldier/vo/outbreakstatusiscode.wav");
Schema.voices:Add("Combine", "Overwatch", "Overwatch!", "npc/combine_soldier/vo/overwatch.wav");
Schema.voices:Add("Combine", "Anti-citizen one", "Anti-citizen one.", "npc/combine_soldier/vo/anticitizenone.wav");
Schema.voices:Add("Combine", "Officer down code 3", "Officer down, request all units Code 3 to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav");
Schema.voices:Add("Combine", "Overwatch down", "Overwatch team is down, sector is not controlled.", "npc/combine_soldier/vo/overwatchteamisdown.wav");
Schema.voices:Add("Combine", "Sundown", "Sundown.", "npc/combine_soldier/vo/sundown.wav");
Schema.voices:Add("Combine", "Code 7", "Code 7.", "npc/metropolice/vo/code7.wav");
Schema.voices:Add("Combine", "A 10-30", "I have a 10-30 at my 10-20, responding code 2.", "npc/metropolice/vo/ihave10-30my10-20responding.wav");
Schema.voices:Add("Combine", "Malcompliant 10-107", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav");
Schema.voices:Add("Combine", "A grenade", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav");
Schema.voices:Add("Combine", "10-8s", "10-8, standing by.", "npc/metropolice/vo/ten8standingby.wav");
Schema.voices:Add("Combine", "Is 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav");
Schema.voices:Add("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav");
Schema.voices:Add("Combine", "Standing by", "Standing by.", "npc/combine_soldier/vo/standingby].wav");
Schema.voices:Add("Combine", "Moved now", "Suspect has moved now to..", "npc/metropolice/vo/suspecthasmovednowto.wav");
Schema.voices:Add("Combine", "Ready to go", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav");
Schema.voices:Add("Combine", "Bouncer", "Bouncer, bouncer!", "npc/combine_soldier/vo/bouncerbouncer.wav");
Schema.voices:Add("Combine", "Standard Check", "Uhh..rodger that. Little uh..standard loyalty check procedure 243 my 10-22 intake station, over.", "npc/metropolice/vo/standardloyaltycheck.wav");
Schema.voices:Add("Combine", "Begin scanning", "10-0, begin scanning.", "npc/overwatch/radiovoice/beginscanning10-0.wav");
Schema.voices:Add("Combine", "Complete sentencing", "All protection team units, complete sentencing at will.", "npc/overwatch/radiovoice/completesentencingatwill.wav");
Schema.voices:Add("Combine", "Reinforcement teams", "Reinforcement teams code 3.", "npc/overwatch/radiovoice/reinforcementteamscode3.wav");
Schema.voices:Add("Combine", "Report status", "Local CP teams report status.", "npc/metropolice/vo/localcptreportstatus.wav");
Schema.voices:Add("Combine", "Closing", "Officer closing on suspect.", "npc/overwatch/radiovoice/officerclosingonsuspect.wav");
Schema.voices:Add("Combine", "Investigate and report", "Investigate and report.", "npc/overwatch/radiovoice/investigateandreport.wav");
Schema.voices:Add("Combine", "Amputation", "Immediate amputation.", "npc/overwatch/radiovoice/immediateamputation.wav");
Schema.voices:Add("Combine", "Forward pressure", "All units apply forward pressure.", "npc/overwatch/radiovoice/allunitsapplyforwardpressure.wav");
Schema.voices:Add("Combine", "243 suspect", "All units report status on 243 suspect.", "npc/overwatch/radiovoice/statuson243suspect.wav");
Schema.voices:Add("Combine", "BOL suspect", "All units BOL for 243 suspect.", "npc/overwatch/radiovoice/allunitsbolfor243suspect.wav");
Schema.voices:Add("Combine", "Respond", "Respond.", "npc/overwatch/radiovoice/respond.wav");
Schema.voices:Add("Combine", "Sterilization", "All units begin witness sterilization.", "npc/overwatch/radiovoice/allunitsbeginwhitnesssterilization.wav");
Schema.voices:Add("Combine", "Contain", "Remaining units contain.", "npc/overwatch/radiovoice/remainingunitscontain.wav");
Schema.voices:Add("Combine", "Report please", "Report please.", "npc/overwatch/radiovoice/reportplease.wav");
Schema.voices:Add("Combine", "Stabilization", "Socio-stabilization restored.", "npc/overwatch/radiovoice/sociostabilizationrestored.wav");
Schema.voices:Add("Combine", "Charged with", "Attention, you have been charged with:", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav");
Schema.voices:Add("Combine", "Final sentencing", "Prepare for final sentencing.", "npc/overwatch/radiovoice/prepareforfinalsentencing.wav");
Schema.voices:Add("Combine", "Receive verdict", "Prepare to receive verdict.", "npc/overwatch/radiovoice/preparetoreceiveverdict.wav");
Schema.voices:Add("Combine", "Judged guilty", "You are judged guilty by Civil Protection teams.", "npc/overwatch/radiovoice/youarejudgedguilty.wav");
Schema.voices:Add("Combine", "Capital malcompliance", "Capital malcompliance.", "npc/overwatch/radiovoice/capitalmalcompliance.wav");
Schema.voices:Add("Combine", "Level 5", "Level 5 anti-civil activity.", "npc/overwatch/radiovoice/level5anticivilactivity.wav");
Schema.voices:Add("Combine", "Unrest", "Promoting communal unrest.", "npc/overwatch/radiovoice/promotingcommunalunrest.wav");
Schema.voices:Add("Combine", "Civic trust", "Violation of civic trust.", "npc/overwatch/radiovoice/violationofcivictrust.wav");
Schema.voices:Add("Combine", "In progress", "In progress.", "npc/overwatch/radiovoice/inprogress.wav");
Schema.voices:Add("Combine", "Loyalty check", "Oh I have a failure to comply with loyalty check, tag is possible 10-103m.", "npc/metropolice/vo/loyaltycheckfailure.wav");
Schema.voices:Add("Combine", "Stabilization teams", "Overwatch activate central transport stabilization teams.", "npc/combine_soldier/vo/prison_soldier_activatecentral.wav");
Schema.voices:Add("Combine", "Going", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav");
Schema.voices:Add("Combine", "Look out", "Look out!", "npc/metropolice/vo/lookout.wav");
Schema.voices:Add("Combine", "Any help", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav");
Schema.voices:Add("Combine", "Get in", "Get in.", "vo/trainyard/ba_getin.wav");
Schema.voices:Add("Combine", "Get in here", "Get in here.", "vo/trainyard/ba_inhere01.wav");
Schema.voices:Add("Combine", "Come citizen", "You, citizen, come with me.", "vo/trainyard/ba_youcomewith.wav");
Schema.voices:Add("Combine", "Go on", "Go on.", "vo/trainyard/ba_goon.wav");
Schema.voices:Add("Combine", "No im good", "No, I'm good.", "vo/trainyard/ba_noimgood.wav");
Schema.voices:Add("Combine", "Back up", "Back up.", "vo/trainyard/ba_backup.wav");
Schema.voices:Add("Combine", "I said move", "I said move!", "vo/trainyard/ba_move01.wav");
Schema.voices:Add("Combine", "Tag 10-91d", "Tag 10-91d.", "npc/metropolice/vo/tag10-91d.wav");
Schema.voices:Add("Combine", "Tag One Bug", "Tag One Bug", "npc/metropolice/vo/.wav");
Schema.voices:Add("Combine", "Tag One Necrotic", "Tag one necrotic.", "npc/metropolice/vo/tagonenecrotic.wav");
Schema.voices:Add("Combine", "Tag One Parasitic", "Tag one parasitic.", "npc/metropolice/vo/tagoneparasitic.wav");
Schema.voices:Add("Combine", "0", "Zero.", "npc/combine_soldier/vo/zero.wav");
Schema.voices:Add("Combine", "1", "One.", "npc/combine_soldier/vo/one.wav");
Schema.voices:Add("Combine", "2", "Two.", "npc/combine_soldier/vo/two.wav");
Schema.voices:Add("Combine", "3", "Three.", "npc/combine_soldier/vo/three.wav");
Schema.voices:Add("Combine", "4", "Four.", "npc/combine_soldier/vo/four.wav");
Schema.voices:Add("Combine", "5", "Five.", "npc/combine_soldier/vo/five.wav");
Schema.voices:Add("Combine", "6", "Six.", "npc/combine_soldier/vo/six.wav");
Schema.voices:Add("Combine", "7", "Seven.", "npc/combine_soldier/vo/seven.wav");
Schema.voices:Add("Combine", "8", "Eight.", "npc/combine_soldier/vo/eight.wav");
Schema.voices:Add("Combine", "9", "Nine.", "npc/metropolice/vo/nine.wav");
Schema.voices:Add("Combine", "10", "Ten.", "npc/metropolice/vo/ten.wav");
Schema.voices:Add("Combine", "11", "Eleven.", "npc/metropolice/vo/eleven.wav");
Schema.voices:Add("Combine", "12", "Twelve.", "npc/metropolice/vo/twelve.wav");
Schema.voices:Add("Combine", "13", "Thirteen.", "npc/metropolice/vo/thirteen.wav");
Schema.voices:Add("Combine", "14", "Fourteen.", "npc/metropolice/vo/fourteen.wav");
Schema.voices:Add("Combine", "15", "Fifteen.", "npc/metropolice/vo/fifteen.wav");
Schema.voices:Add("Combine", "16", "Sixteen.", "npc/metropolice/vo/sixteen.wav");
Schema.voices:Add("Combine", "17", "Seventeen.", "npc/metropolice/vo/seventeen.wav");
Schema.voices:Add("Combine", "18", "Eighteen.", "npc/metropolice/vo/eighteen.wav");
Schema.voices:Add("Combine", "19", "Nineteen.", "npc/metropolice/vo/nineteen.wav");
Schema.voices:Add("Combine", "20", "Twenty.", "npc/metropolice/vo/twenty.wav");
Schema.voices:Add("Combine", "30", "Thirty.", "npc/metropolice/vo/thirty.wav");
Schema.voices:Add("Combine", "40", "Fourty.", "npc/metropolice/vo/fourty.wav");
Schema.voices:Add("Combine", "50", "Fifty.", "npc/metropolice/vo/fifty.wav");
Schema.voices:Add("Combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav");
Schema.voices:Add("Combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav");
Schema.voices:Add("Combine", "10-8", "Unit is on duty, 10-8.","npc/metropolice/vo/unitisonduty10-8.wav");
Schema.voices:Add("Combine", "10-14", "Holding, I'm at 10-14 Duty at code four.", "npc/metropolice/vo/holdingon10-14duty.wav");
Schema.voices:Add("Combine", "10-15", "Prepare for 10-15","npc/metropolice/vo/preparefor1015.wav");
Schema.voices:Add("Combine", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav");
Schema.voices:Add("Combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/ten97.wav");
Schema.voices:Add("Combine", "10-91", "10-91d count is..", "npc/metropolice/vo/ten91dcountis.wav");
Schema.voices:Add("Combine", "10-97 goa", "10-97, the suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav");
Schema.voices:Add("Combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav");
Schema.voices:Add("Combine", "10-99", "Officer down I am 10-99! Repeat I am 10-99!", "npc/metropolice/vo/officerdowniam10-99.wav");
Schema.voices:Add("Combine", "10-108", "We have a 10-108!","npc/metropolice/vo/wehavea10-108.wav");
Schema.voices:Add("Combine", "10-30", "I have a 10-30, my 10-20, responding code 2.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav");
Schema.voices:Add("Combine", "10-107 here", "I have a 10-107 here, send Airwatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav");
Schema.voices:Add("Combine", "148", "148. Resisting arrest.", "npc/overwatch/radiovoice/resistingpacification148.wav");
Schema.voices:Add("Combine", "408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav");
Schema.voices:Add("Combine", "95", "95, illegal carrying.", "npc/overwatch/radiovoice/illegalcarrying95.wav");
Schema.voices:Add("Combine", "69", "69, posession of resources.", "npc/overwatch/radiovoice/posession69.wav");
Schema.voices:Add("Combine", "603", "603, unlawful entry.", "npc/overwatch/radiovoice/unlawfulentry603.wav");
Schema.voices:Add("Combine", "94", "94, weapon.", "npc/overwatch/radiovoice/weapon94.wav");
Schema.voices:Add("Combine", "51", "51b, threat to property.", "npc/overwatch/radiovoice/threattoproperty51b.wav");
Schema.voices:Add("Combine", "103", "10-103m, disturbance by mentally unfit.", "npc/overwatch/radiovoice/disturbancemental10-103m.wav");
Schema.voices:Add("Combine", "243", "243, assault on protection team.", "npc/overwatch/radiovoice/assault243.wav");
Schema.voices:Add("Combine", "27", "27, attempted crime.", "npc/overwatch/radiovoice/attemptedcrime27.wav");
Schema.voices:Add("Combine", "63", "63, criminal trespass.", "npc/overwatch/radiovoice/criminaltrespass63.wav");
Schema.voices:Add("Combine", "51", "51, non-sanctioned arson.", "npc/overwatch/radiovoice/nonsanctionedarson51.wav");
Schema.voices:Add("Combine", "99", "99, reckless operation.", "npc/overwatch/radiovoice/recklessoperation99.wav");
Schema.voices:Add("Combine", "507", "507, public non-compliance.", "npc/overwatch/radiovoice/publicnoncompliance507.wav");
Schema.voices:Add("Combine", "187", "Suspect is now 187.", "npc/overwatch/radiovoice/suspectisnow187.wav");
Schema.voices:Add("Combine", "heis", "There he is!", "npc/metropolice/vo/thereheis.wav");
Schema.voices:Add("Combine", "Hunting", "10-0, 10-0, viscerator is hunting.", "npc/metropolice/vo/tenzerovisceratorishunting.wav");
Schema.voices:Add("Combine", "Responding", "Responding.", "npc/metropolice/vo/responding2.wav");
Schema.voices:Add("Combine", "Contact Suspect", "Contact with 243 suspect. My 10-20 is..", "npc/metropolice/vo/contactwith243suspect.wav");
Schema.voices:Add("Combine", "Roller", "Roller.", "npc/metropolice/vo/roller.wav");
Schema.voices:Add("Combine", "Line", "Line.", "npc/metropolice/vo/line.wav");
Schema.voices:Add("Combine", "Grenade", "Grenade!", "npc/metropolice/vo/grenade.wav");
Schema.voices:Add("Combine", "Hold", "Hold it.", "npc/metropolice/vo/holdit.wav");
Schema.voices:Add("Combine", "Position", "Protection team, hold this position.", "npc/metropolice/vo/holdthisposition.wav");
Schema.voices:Add("Combine", "Down", "Is down!", "npc/metropolice/vo/isdown.wav");
Schema.voices:Add("Combine", "Take down", "Take him down!", "npc/metropolice/takedown.wav");
Schema.voices:Add("Combine", "Sacrifice code 1", "All units sacrifice code 1 and maintain this CP.", "npc/metropolice/vo/sacrificecode1maintaincp.wav");
Schema.voices:Add("Combine", "Serve", "Serve.", "npc/metropolice/vo/serve.wav");
Schema.voices:Add("Combine", "Stick", "Stick.", "npc/metropolice/vo/stick.wav");
Schema.voices:Add("Combine", "Activate Central", "Overwatch activate central transport stabilization teams.", "npc/combine_soldier/vo/prison_soldier_activatecentral.wav");
Schema.voices:Add("Combine", "Boomers inbound", "Overwatch confirm status, boomers inbound, prepare for special supression and report.", "npc/combine_soldier/vo/prison_soldier_boomersinbound.wav");
Schema.voices:Add("Combine", "Grid", "Grid!", "npc/combine_soldier/vo/grid.wav");
Schema.voices:Add("Combine", "Kilo", "Kilo!", "npc/combine_soldier/vo/kilo.wav");
Schema.voices:Add("Combine", "Echo", "Echo!", "npc/combine_soldier/vo/echo.wav");
Schema.voices:Add("Combine", "Striker", "Striker!", "npc/combine_soldier/vo/striker.wav");
Schema.voices:Add("Combine", "Judge", "Judge!", "npc/combine_soldier/vo/judge.wav");
Schema.voices:Add("Combine", "Ghost", "Ghost!", "npc/combine_soldier/vo/ghost.wav");
Schema.voices:Add("Combine", "Sword", "Sword!", "npc/combine_soldier/vo/sword.wav");
Schema.voices:Add("Combine", "Union", "Union!", "npc/metropolice/vo/union.wav");
Schema.voices:Add("Combine", "Helix", "Helix!", "npc/combine_soldier/vo/helix.wav");
Schema.voices:Add("Combine", "Storm", "Storm!", "npc/combine_soldier/vo/storm.wav");
Schema.voices:Add("Combine", "Spear", "Spear!", "npc/combine_soldier/vo/spear.wav");
Schema.voices:Add("Combine", "Ranger", "Ranger!", "npc/combine_soldier/vo/ranger.wav");
Schema.voices:Add("Combine", "Dash", "Dash!", "npc/combine_soldier/vo/dash.wav");
Schema.voices:Add("Combine", "Apex", "Apex!", "npc/combine_soldier/vo/apex.wav");
Schema.voices:Add("Combine", "Preserve", "Preserve!", "npc/metropolice/vo/preserve.wav");
Schema.voices:Add("Combine", "Pressure", "Pressure!", "npc/metropolice/vo/pressure.wav");
Schema.voices:Add("Combine", "Phantom", "Phantom!", "npc/combine_soldier/vo/phantom.wav");
Schema.voices:Add("Combine", "Stinger", "Stinger!", "npc/combine_soldier/vo/stinger.wav");
Schema.voices:Add("Combine", "Shadow", "Shadow!", "npc/combine_soldier/vo/shadow.wav");
Schema.voices:Add("Combine", "Savage", "Savage!", "npc/combine_soldier/vo/savage.wav");
Schema.voices:Add("Combine", "Reaper", "Reaper!", "npc/combine_soldier/vo/reaper.wav");
Schema.voices:Add("Combine", "Victor", "Victor!", "npc/metropolice/vo/victor.wav");
Schema.voices:Add("Combine", "Sector", "Sector!", "npc/metropolice/vo/sector.wav");
Schema.voices:Add("Combine", "Inject", "Inject!", "npc/metropolice/vo/inject.wav");
Schema.voices:Add("Combine", "Dagger", "Dagger!", "npc/combine_soldier/vo/dagger.wav");
Schema.voices:Add("Combine", "Blade", "Blade!", "npc/combine_soldier/vo/blade.wav");
Schema.voices:Add("Combine", "Razor", "Razor!", "npc/combine_soldier/vo/razor.wav");
Schema.voices:Add("Combine", "Nomad", "Nomad!", "npc/combine_soldier/vo/nomad.wav");
Schema.voices:Add("Combine", "Vamp", "Vamp!", "npc/combine_soldier/vo/vamp.wav");
Schema.voices:Add("Combine", "Nova", "Nova!", "npc/combine_soldier/vo/nova.wav");
Schema.voices:Add("Combine", "Mace", "Mace!", "npc/combine_soldier/vo/mace.wav");
Schema.voices:Add("Combine", "Jury", "Jury!", "npc/metropolice/vo/jury.wav");
Schema.voices:Add("Combine", "King", "King!", "npc/metropolice/vo/king.wav");
Schema.voices:Add("Combine", "Lock", "Lock!", "npc/metropolice/vo/lock.wav");
Schema.voices:Add("Combine", "Vice", "Vice!", "npc/metropolice/vo/vice.wav");
Schema.voices:Add("Combine", "Zone", "Zone!", "npc/metropolice/vo/zone.wav");
Schema.voices:Add("Combine", "On Visual", "Acquiring on visual.", "npc/metropolice/vo/acquiringonvisual.wav");
Schema.voices:Add("Combine", "Affirmative 2", "Affirmative.", "npc/metropolice/vo/affirmative2.wav");
Schema.voices:Add("Combine", "BOL", "All Units, BOL, We have Thirty Four's At...", "npc/metropolice/vo/allunitsbol34sat.wav");
Schema.voices:Add("Combine", "Code2", "All units, Code two.", "npc/metropolice/vo/allunitscode2.wav");
Schema.voices:Add("Combine", "Pickup 647e", "Anyone pickup uhh..647e reading?", "npc/metropolice/vo/anyonepickup647e.wav");
Schema.voices:Add("Combine", "Back me up", "Back me up, I'm out!.", "npc/metropolice/vo/backmeupImout.wav");
Schema.voices:Add("Combine", "Break Cover", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav");
Schema.voices:Add("Combine", "No 647", "Clear, no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav");
Schema.voices:Add("Combine", "Dead Body", "Dead body Count is...", "npc/metropolice/vo/dbcountis.wav");
Schema.voices:Add("Combine", "Deserviced Area", "Deserviced Area.", "npc/metropolice/vo/deservicedarea.wav");
Schema.voices:Add("Combine", "Establish Perimiter", "CP We need to establish perimiter at...", "npc/metropolice/vo/cpweneedtoestablishperimiterat.wav");
Schema.voices:Add("Combine", "Check miscount", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav");
Schema.voices:Add("Combine", "Airwatch 243", "CP we need Airwatch to BOL for that 243.", "npc/metropolice/vo/checkformiscount.wav");
Schema.voices:Add("Combine", "Bugs loose", "We got bugs on the loose.", "npc/metropolice/vo/bugsontheloose.wav");
Schema.voices:Add("Combine", "Is Passive", "Is Passive.", "npc/metropolice/vo/ispassive.wav");
Schema.voices:Add("Combine", "Move along.", "Move along.", "npc/metropolice/vo/movealong.wav");
Schema.voices:Add("Combine", "Move it 2", "Move it!", "npc/metropolice/vo/moveit.wav");
Schema.voices:Add("Combine", "Suspect 11-6", "Suspect 11-6 my 10-20 is..", "npc/metropolice/vo/suspect11-6my1020is.wav");
Schema.voices:Add("Combine", "Victor", "Victor!", "npc/metropolice/vo/victor.wav");
Schema.voices:Add("Combine", "Non Tagged viromes", "Non tagged viromes here.", "npc/metropolice/vo/nontaggedviromeshere.wav");
Schema.voices:Add("Combine", "Officer under fire", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav");
Schema.voices:Add("Combine", "Quick", "Quick!", "npc/metropolice/vo/quick.wav");
Schema.voices:Add("Combine", "Got him again", "Got him again. Suspect is 10-20 at..", "npc/metropolice/vo/gothimagainsuspect10-20at.wav");
Schema.voices:Add("Combine", "Accomplice", "I got 1 accomplice here.", "npc/metropolice/vo/gotoneaccomplicehere.wav");
Schema.voices:Add("Combine", "Code 100", "Code 100.","npc/metropolice/vo/code100.wav");
Schema.voices:Add("Combine", "Teamdown", "Overwatch team is down this sector is not controlled!","npc/combine_soldier/vo/overwatchteamisdown.wav");
Schema.voices:Add("Combine", "Reinforcement", "Overwatch request reinforcement.","npc/combine_soldier/vo/overwatchrequestreinforcement.wav");
Schema.voices:Add("Combine", "10-78", "Dispatch I need 10-78, officer in trouble!","npc/metropolice/vo/dispatchIneed10-78.wav");
Schema.voices:Add("Combine", "Close Suspect", "All Units! Close on Suspect!","npc/metropolice/vo/allunitscloseonsuspect.wav");
Schema.voices:Add("Combine", "Ready weapons", "Ready weapons, possible hostiles inbound.","npc/combine_soldier/vo/readyweaponshostilesinbound.wav");
Schema.voices:Add("Combine", "Charges", "Ready charges!","npc/combine_soldier/vo/readycharges.wav");
Schema.voices:Add("Combine", "Sector Secured", "Sector is Secured, no viscon.","npc/combine_soldier/vo/sectorissecurenovison.wav");
Schema.voices:Add("Combine", "Confirmed", "Contact Confirmed, Prosecuting!","npc/combine_soldier/vo/contactconfirmprosecuting.wav");
Schema.voices:Add("Combine", "Stabilization", "Stabilization team holding in position.","npc/combine_soldier/vo/stabilizationteamholding.wav");
Schema.voices:Add("Combine", "Infestation", "We are in an infestation zone.","npc/combine_soldier/vo/weareinaninfestationzone.wav");
Schema.voices:Add("Combine", "Medical", "Request Medical!","npc/combine_soldier/vo/requestmedical.wav");
Schema.voices:Add("Combine", "Stable at", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav");
Schema.voices:Add("Combine", "DB Here", "Uhh...we got a DB here, cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav");
Schema.voices:Add("Combine", "Preparing", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav");
Schema.voices:Add("Combine", "Possible 647", "Possible 647e here, request Airwatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav");
Schema.voices:Add("Combine", "Possible 10-103", "Possible 10-103, my location, alert tag units.", "npc/metropolice/vo/possible10-103alerttagunits.wav");
Schema.voices:Add("Combine", "Position to", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav");
Schema.voices:Add("Combine", "Outland Biotic", "I got an outland biotic in here.", "npc/metropolice/vo/outlandbioticinhere.wav");
Schema.voices:Add("Combine", "Stay alert", "Stay alert, report sight lines.","npc/combine_soldier/vo/stayalertreportsightlines.wav");
Schema.voices:Add("Combine", "Positions", "All units move to arrest positions.","npc/metropolice/vo/movetoarrestpositions.wav");
Schema.voices:Add("Combine", "Pacifying", "Pacifying!","npc/metropolice/vo/pacifying.wav");
Schema.voices:Add("Combine", "Prosecute Final", "Ready to prosecute malcompliant citizen final warning issued!","npc/metropolice/vo/readytoprosecutefinalwarning.wav");
Schema.voices:Add("Combine", "Clearcode100", "Clear and code 100.","npc/metropolice/vo/clearandcode100.wav");
Schema.voices:Add("Combine", "Still 647e", "Still getting a 647e from local surveillance.","npc/metropolice/vo/stillgetting647e.wav");
Schema.voices:Add("Combine", "Blip", "Catch that blip on the stabilization readout?","npc/metropolice/vo/catchthatbliponstabilization.wav");
Schema.voices:Add("Combine", "Ripcord", "Ripcord.","npc/combine_soldier/vo/ripcord.wav");
Schema.voices:Add("Combine", "Ripcord 2", "Ripcord, ripcord!","npc/combine_soldier/vo/ripcordripcord.wav");
Schema.voices:Add("Combine", "Condemned", "Condemned zone.", "npc/metropolice/vo/condemnedzone.wav");
Schema.voices:Add("Combine", "Confirm Priority", "Confirm priority 1 sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav");
Schema.voices:Add("Combine", "Converging", "Converging.", "npc/metropolice/vo/converging.wav");
Schema.voices:Add("Combine", "CP Compromised", "CP is compromised. Reestablish!", "npc/metropolice/vo/cpiscompromised.wav");
Schema.voices:Add("Combine", "Overrun", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav");
Schema.voices:Add("Combine", "CP report in", "CP requests all units..uh..location report in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav");
Schema.voices:Add("Combine", "Designate", "Designate suspect as..", "npc/metropolice/vo/designatesuspectas.wav");
Schema.voices:Add("Combine", "Dismounting", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav");
Schema.voices:Add("Combine", "Disp Report", "Disp reports, suspect incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav");
Schema.voices:Add("Combine", "Disp Updating", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav");
Schema.voices:Add("Combine", "Distribution", "Distribution block.", "npc/metropolice/vo/distributionblock.wav");
Schema.voices:Add("Combine", "Hardpoint Scanning", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav");
Schema.voices:Add("Combine", "Hes 148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav");
Schema.voices:Add("Combine", "Up there", "He's up there!", "npc/metropolice/vo/hesupthere.wav");
Schema.voices:Add("Combine", "Hiding last", "Hiding, last seen at range..", "npc/metropolice/vo/hidinglastseenatrange.wav");
Schema.voices:Add("Combine", "High Priority", "High priority region.", "npc/metropolice/vo/highpriorityregion.wav");
Schema.voices:Add("Combine", "Industrial", "Industrial zone.", "npc/metropolice/vo/industrialzone.wav");
Schema.voices:Add("Combine", "Infested", "Infested zone.", "npc/metropolice/vo/infestedzone.wav");
Schema.voices:Add("Combine", "In position at", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav");
Schema.voices:Add("Combine", "In position 1", "In position on 1 ready.", "npc/metropolice/vo/inpositionononeready.wav");
Schema.voices:Add("Combine", "At hardpoint", "Is at hardpoint, ready to prosecute.", "npc/metropolice/vo/isathardpointreadytoprosecute.wav");
Schema.voices:Add("Combine", "Is closing", "Is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav");
Schema.voices:Add("Combine", "Proceed", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav");
Schema.voices:Add("Combine", "At location", "Protect teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav");
Schema.voices:Add("Combine", "PT go again", "PT go again.", "npc/metropolice/vo/ptgoagain.wav");
Schema.voices:Add("Combine", "Failure to", "Failure to comply with the civil will.", "npc/overwatch/radiovoice/failuretocomply.wav");
Schema.voices:Add("Combine", "OffWorld", "Permanent off-world service assignment.", "npc/overwatch/radiovoice/permanentoffworld.wav");
Schema.voices:Add("Combine", "Visual", "Attention: Prepare visual download of anti-citizen one.", "npc/overwatch/radiovoice/preparevisualdownload.wav");
Schema.voices:Add("Combine", "100 credits", "Rank leader, reminder: 100 sterilized credits qualifies non-mechanical reproduction simulation.", "npc/overwatch/radiovoice/reminder100credits.wav");
Schema.voices:Add("Combine", "Replacement", "Reminder: Memory replacement is the first step towards rank privileges.", "npc/overwatch/radiovoice/remindermemoryreplacement.wav");
Schema.voices:Add("Combine", "Incursion", "Restricted incursion in progress.", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav");
Schema.voices:Add("Combine", "Reward Notice", "Reward notice, protection team member: Your family cohesion is preserved.", "npc/overwatch/radiovoice/rewardnotice.wav");
Schema.voices:Add("Combine", "Suspend", "Suspend negotiations.", "npc/overwatch/radiovoice/suspendnegotiations.wav");
Schema.voices:Add("Combine", "Are Charged", "You are charged with terminal violation 148, 243, 245.", "npc/overwatch/radiovoice/youarechargedwithterminal.wav");
Schema.voices:Add("Combine", "Report on", "Local protection team units, report on..", "npc/overwatch/radiovoice/reporton.wav");
Schema.voices:Add("Combine", "No viscon", "No viscon", "npc/combine_soldier/vo/noviscon.wav");
Schema.voices:Add("Combine", "Contact", "Contact.", "npc/combine_soldier/vo/contact.wav");
Schema.voices:Add("Combine", "Contact confirmed", "Contact confirmed, prosecuting.", "npc/combine_soldier/vo/contactconfirmprosecuting.wav");
Schema.voices:Add("Combine", "Team deployed", "Team is deployed and scanning.", "npc/combine_soldier/vo/teamdeployedandscanning.wav");
Schema.voices:Add("Combine", "Code3", "Reinforcement teams, code 3!", "npc/metropolice/vo/reinforcementteamscode3.wav");
Schema.voices:Add("Combine", "Report Sights", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav");
Schema.voices:Add("Combine", "Repurposed", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav");
Schema.voices:Add("Combine", "Low on", "Running low on veridcts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav");
Schema.voices:Add("Combine", "Shots fired", "Shots fired, hostile malignants here.", "npc/metropolice/vo/shotsfiredhostilemalignants.wav");
Schema.voices:Add("Combine", "Jurisdiction", "Stabilization jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav");
Schema.voices:Add("Combine", "High speed", "All units be advised, subject is now high speed.", "npc/metropolice/vo/subjectisnowhighspeed.wav");
Schema.voices:Add("Combine", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav");
Schema.voices:Add("Combine", "UTL that", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav");
Schema.voices:Add("Combine", "Non Patrol", "Non patrol region.", "npc/metropolice/vo/nonpatrolregion.wav");
Schema.voices:Add("Combine", "Non-citizen", "Non-citizen.", "npc/metropolice/vo/noncitizen.wav");
Schema.voices:Add("Combine", "No contact", "No contact.", "npc/metropolice/vo/nocontact.wav");
Schema.voices:Add("Combine", "Hardpoint 2", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint2.wav");
Schema.voices:Add("Combine", "Match on", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav");
Schema.voices:Add("Combine", "Hiding Range", "Hiding, last seen at range..", "npc/metropolice/vo/hidinglastseenatrange.wav");
Schema.voices:Add("Combine", "Firing ", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav");
Schema.voices:Add("Combine", "Unit deserviced", "Unit deserviced.", "npc/overwatch/radiovoice/unitdeserviced.wav");
Schema.voices:Add("Combine", "Down at", "Unit down at..", "npc/overwatch/radiovoice/unitdownat.wav");
Schema.voices:Add("Combine", "Verdict is", "Suspect is judged malignant. Verdict code is..", "npc/overwatch/radiovoice/suspectmalignantverdictcodeis.wav");
Schema.voices:Add("Combine", "Fracture", "Social fracture in progress. Respond.", "npc/overwatch/radiovoice/socialfractureinprogress.wav");
Schema.voices:Add("Combine", "Recalibrate", "Team, recalibrate socio-scan.", "npc/overwatch/radiovoice/recalibratesocioscan.wav");
Schema.voices:Add("Combine", "Premature", "Premature mission termination will result in..", "npc/overwatch/radiovoice/prematuremissiontermination.wav");
Schema.voices:Add("Combine", "Lock down", "Protection team, lock down your location. Sacrifice code..", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav");
Schema.voices:Add("Combine", "Leaders", "Attention stabilization team leaders: Report deserviced units to sterilized body count ratios for reinforcement reward or removal processing.", "npc/overwatch/radiovoice/leadersreportratios.wav");
Schema.voices:Add("Combine", "Reproduction", "50% reproduction credits.", "npc/overwatch/radiovoice/halfreproductioncredits.wav");
Schema.voices:Add("Combine", "Treat", "Stabilization team: Failure to treat identified local outbreak will foreseen recall and recycle.", "npc/overwatch/radiovoice/failuretotreatoutbreak.wav");
Schema.voices:Add("Combine", "Populcate", "Disassociation from the civic populace.", "npc/overwatch/radiovoice/disassociationfromcivic.wav");
Schema.voices:Add("Combine", "Destruction", "Destruction of corporal social protection units.", "npc/overwatch/radiovoice/destructionofcpt.wav");
Schema.voices:Add("Combine", "Verdict code is", "All units: Verdict code is..", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav");
Schema.voices:Add("Combine", "Terminal", "All units deliver terminal verdict immediately.", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav");
Schema.voices:Add("Combine", "All teams", "All teams respond code 3.", "npc/overwatch/radiovoice/allteamsrespondcode3.wav");
Schema.voices:Add("Combine", "Possible miscount", "Airwatch reports possible miscount.", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav");
Schema.voices:Add("Combine", "No activity", "Airwatch copies no activity.", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav");
Schema.voices:Add("Combine", "Accomplices", "Protection team, be advised: Accomplices operating in area.", "npc/overwatch/radiovoice/accomplicesoperating.wav");
Schema.voices:Add("Combine", "Target", "Target.", "npc/combine_soldier/vo/target.wav");
Schema.voices:Add("Combine", "Target Compromised", "Target compromised, move in move in!", "npc/combine_soldier/vo/targetcompromisedmovein.wav");
Schema.voices:Add("Combine", "Target Contact At", "Target contact at...", "npc/combine_soldier/vo/targetcontactat.wav");
Schema.voices:Add("Combine", "Target Contained", "Overwatch, target contained.", "npc/combine_soldier/vo/overwatchtargetcontained.wav");
Schema.voices:Add("Combine", "Target Ineffective", "Target ineffective!", "npc/combine_soldier/vo/targetineffective.wav");
Schema.voices:Add("Combine", "Target My Radial", "Target my radial.", "npc/combine_soldier/vo/targetmyradial.wav");
Schema.voices:Add("Combine", "Target One", "Target one.", "npc/combine_soldier/vo/targetone.wav");
Schema.voices:Add("Combine", "Target One Sterilized", "Overwatch target one sterilized.", "npc/combine_soldier/vo/overwatchtarget1sterilized.wav");
Schema.voices:Add("Combine", "Can 1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav");
Schema.voices:Add("Combine", "Can 2", "Pick... up... the can.", "npc/metropolice/vo/pickupthecan2.wav");
Schema.voices:Add("Combine", "Can 3", "I said pickup the can!", "npc/metropolice/vo/pickupthecan3.wav");
Schema.voices:Add("Combine", "Can 4", "Now, put it in the trash can.", "npc/metropolice/vo/putitinthetrash1.wav");
Schema.voices:Add("Combine", "Can 5", "I said put it in the trash can!", "npc/metropolice/vo/putitinthetrash2.wav");
Schema.voices:Add("Combine", "Chatter1", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_bunker1.wav");
Schema.voices:Add("Combine", "Chatter2", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_bunker2.wav");
Schema.voices:Add("Combine", "Chatter3", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_containD8.wav");
Schema.voices:Add("Combine", "Chatter4", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_fallback_b4.wav");
Schema.voices:Add("Combine", "Chatter5", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_leader9dead.wav");
Schema.voices:Add("Combine", "Chatter6", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_negativecontainment.wav");
Schema.voices:Add("Combine", "Chatter7", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_prosecuteD7");
Schema.voices:Add("Combine", "Chatter8", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_sundown3dead.wav");
Schema.voices:Add("Combine", "Chatter9", "*Indistinct radio chatter*", "npc/combine_soldier/vo/prison_soldier_tohighpoints.wav");

if (CLIENT) then
table.sort(Schema.voices.stored.normalVoices, function(a, b) return a.command < b.command; end);

 for k, v in pairs(Schema.voices.stored.normalVoices) do
  if v.faction == "Combine" then
   Clockwork.directory:AddCode("Civil Protection", [[
    <div class="auraInfoTitle">]]..string.upper(v.command)..[[</div>
    <div class="auraInfoText">]]..v.phrase..[[</div>
   ]], true);
 end;
end;
end;

local PLUGIN = PLUGIN;

-- Dispatch voices. Remove everything up to the next comment to remove all Dispatch voices.
Schema.voices:AddDispatch("404zone", "404zone.", "npc/overwatch/radiovoice/404zone.wav");
Schema.voices:AddDispatch("Accomplices Operating", "Protection Team verifired, accomplices operating an area.", "npc/overwatch/radiovoice/accomplicesoperating.wav");
Schema.voices:AddDispatch("Administer", "Administer.", "npc/overwatch/radiovoice/administer.wav");
Schema.voices:AddDispatch("Airwatchcopies Noactivity", "Airwatch copies is no activily in location.", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav");
Schema.voices:AddDispatch("Airwatch Report Iscount", "Airwatch reports possiblem iscount.", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav");
Schema.voices:AddDispatch("62 Alarms", "62 Alarms.", "npc/overwatch/radiovoice/alarms62.wav");
Schema.voices:AddDispatch("Respond Code3", "All Team, respond code 3.", "npc/overwatch/radiovoice/allteamrespondcode3.wav");
Schema.voices:AddDispatch("Apply Pressure", "All unit, apply forward pressure.", "npc/overwatch/radiovoice/allunitapplyforwardpressure.wav");
Schema.voices:AddDispatch("Unit Sat", "All unit sat.", "npc/overwatch/radiovoice/allunitsat.wav");
Schema.voices:AddDispatch("Whitnesssterilization", "All units, begin with Whitnesssterilization.", "npc/overwatch/radiovoice/allunitbeginwithwhitnesssterilization.wav");
Schema.voices:AddDispatch("Deliver Terminal Verdict", "All units, devlier terminal verdict immediately.", "npc/overwatch/radiovoice/Allunitsdevlierterminalverdict.wav");
Schema.voices:AddDispatch("Return Code12", "All units, return to code 12.", "npc/overwatch/radiovoice/allunitstocode12.wav");
Schema.voices:AddDispatch("Verdict Code", "All units, verdict code is...", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav");
Schema.voices:AddDispatch("Verdict Codeon", "All units, verdict code on suspect", "npc/overwatch/radiovoice/allunitsverdictcodeonsuspect.wav");
Schema.voices:AddDispatch("Amputate", "Amputate.", "npc/overwatch/radiovoice/amputate.wav");
Schema.voices:AddDispatch("AntiCitizen", "Anti-Citizen.", "npc/overwatch/radiovoice/anticitizen.wav");
Schema.voices:AddDispatch("Apply", "Apply.", "npc/overwatch/radiovoice/apply.wav");
Schema.voices:AddDispatch("Attention", "Attention!", "npc/overwatch/radiovoice/attention.wav");
Schema.voices:AddDispatch("Charged with", "Attention, you have been charged with...", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav");
Schema.voices:AddDispatch("Block", "Block.", "npc/overwatch/radiovoice/block.wav");
Schema.voices:AddDispatch("Canalblock", "Canalblock.", "npc/overwatch/radiovoice/canalblock.wav");
Schema.voices:AddDispatch("Capital Malcompliance", "Capital Malcompliance.", "npc/overwatch/radiovoice/capitalmalcompliance.wav");
Schema.voices:AddDispatch("Cauterize", "Cauterize.", "npc/overwatch/radiovoice/cauterize.wav");
Schema.voices:AddDispatch("Citizen", "Citizen.", "npc/overwatch/radiovoice/citizen.wav");
Schema.voices:AddDispatch("Condemned Zone", "Condemned Zone.", "npc/overwatch/radiovoice/condemnedzone.wav");
Schema.voices:AddDispatch("UPI Alert", "Team, confirm UPI alert.", "npc/overwatch/radiovoice/confirmupialert.wav");
Schema.voices:AddDispatch("63Trespass", "63 criminal trespass.", "npc/overwatch/radiovoice/criminaltrespass63.wav");
Schema.voices:AddDispatch("Defender", "Defender!", "npc/overwatch/radiovoice/defender.wav");
Schema.voices:AddDispatch("Restricted Block", "Restricted Block.", "npc/overwatch/radiovoice/deservicedarea.wav");
Schema.voices:AddDispatch("8", "Eight.", "npc/overwatch/radiovoice/eight.wav");
Schema.voices:AddDispatch("Examine", "Examine!", "npc/overwatch/radiovoice/examine.wav");
Schema.voices:AddDispatch("Failure To Comply", "Failure to comply with the civil will.", "npc/overwatch/radiovoice/failuretocomply.wav");
Schema.voices:AddDispatch("Final Verdict", "Final verdict administered", "npc/overwatch/radiovoice/finalverdictadministered.wav");
Schema.voices:AddDispatch("5", "Five.", "npc/overwatch/radiovoice/five.wav");
Schema.voices:AddDispatch("4", "Four.", "npc/overwatch/radiovoice/four.wav");
Schema.voices:AddDispatch("Freeman", "Freeman!", "npc/overwatch/radiovoice/freeman.wav");
Schema.voices:AddDispatch("Hero", "Hero!", "npc/overwatch/radiovoice/hero.wav");
Schema.voices:AddDispatch("High Priority Region", "High Priority region.", "npc/overwatch/radiovoice/highpriorityregion.wav");
Schema.voices:AddDispatch("Industrial Zone", "Industrial zone.", "npc/overwatch/radiovoice/industrialzone.wav");
Schema.voices:AddDispatch("Infect", "Infection.", "npc/overwatch/radiovoice/infection.wav");
Schema.voices:AddDispatch("Infested Zone", "Infested Zone.", "npc/overwatch/radiovoice/infestedzone.wav");
Schema.voices:AddDispatch("Lock", "Lock!", "npc/overwatch/radiovoice/lock.wav");
Schema.voices:AddDispatch("Inject", "Inject!", "npc/overwatch/radiovoice/inject.wav");
Schema.voices:AddDispatch("Innoculate", "Innoculate!", "npc/overwatch/radiovoice/innoculate.wav");
Schema.voices:AddDispatch("In Progress", "In Progress.", "npc/overwatch/radiovoice/inprogress.wav");
Schema.voices:AddDispatch("Interlock", "Interlock!", "npc/overwatch/radiovoice/interlock.wav");
Schema.voices:AddDispatch("Investigate", "Investigate.", "npc/overwatch/radiovoice/investigate.wav");
Schema.voices:AddDispatch("Investigate And Report", "Investigate and report!", "npc/overwatch/radiovoice/investigateandreport.wav");
Schema.voices:AddDispatch("Is Now", "Is now.", "npc/overwatch/radiovoice/isnow.wav");
Schema.voices:AddDispatch("Isolate", "Isolate.", "npc/overwatch/radiovoice/isolate.wav");
Schema.voices:AddDispatch("Jury", "Jury!", "npc/overwatch/radiovoice/jury.wav");
Schema.voices:AddDispatch("King", "King!", "npc/overwatch/radiovoice/king.wav");
Schema.voices:AddDispatch("Line", "Line!", "npc/overwatch/radiovoice/line.wav");
Schema.voices:AddDispatch("Lockdown Location", "Protection Team, lockdown your location sacrifice code.", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav");
Schema.voices:AddDispatch("Biosignal Lost", "Lost Biosignal for protection team unit.", "npc/overwatch/radiovoice/lostbiosignalforunit.wav");
Schema.voices:AddDispatch("Nine", "Nine.", "npc/overwatch/radiovoice/nine.wav");
Schema.voices:AddDispatch("Noncitizen", "Non Citizen.", "npc/overwatch/radiovoice/noncitizen.wav");
Schema.voices:AddDispatch("Non Patrol Region", "Non patrol region!", "npc/overwatch/radiovoice/nonpatrolregion.wav");
Schema.voices:AddDispatch("Officer At", "Officer at...", "npc/overwatch/radiovoice/officerat.wav");
Schema.voices:AddDispatch("Officer Closing On Suspect", "Officer closing on suspect.", "npc/overwatch/radiovoice/officerclosingonsuspect.wav");
Schema.voices:AddDispatch("1", "One.", "npc/overwatch/radiovoice/one.wav");
Schema.voices:AddDispatch("OFF2", "*Radio turns off*", "npc/overwatch/radiovoice/off2.wav");
Schema.voices:AddDispatch("OFF4", "*Radio goes off*", "npc/overwatch/radiovoice/off4.wav");
Schema.voices:AddDispatch("ON1", "*Radio goes on*", "npc/overwatch/radiovoice/on1.wav");
Schema.voices:AddDispatch("ON3", "*Radio turns on*", "npc/overwatch/radiovoice/on3.wav");
Schema.voices:AddDispatch("Outlandzone", "Outlandzone.", "npc/overwatch/radiovoice/outlandzone.wav");
Schema.voices:AddDispatch("Patrol", "Patrol!", "npc/overwatch/radiovoice/patrol.wav");
Schema.voices:AddDispatch("Preserve", "Preserve.", "npc/overwatch/radiovoice/preserve.wav");
Schema.voices:AddDispatch("69 posession", "69 posession of recources.", "npc/overwatch/radiovoice/posession69.wav");
Schema.voices:AddDispatch("Pressure", "Pressure.", "npc/overwatch/radiovoice/pressure.wav");
Schema.voices:AddDispatch("Production Block", "Prdouction block.", "npc/overwatch/radiovoice/production block.wav");
Schema.voices:AddDispatch("Promoting Unrest", "Promoting communal unrest.", "npc/overwatch/radiovoice/promotingcommunalunrest.wav");
Schema.voices:AddDispatch("Prosecute", "Prosecute.", "npc/overwatch/radiovoice/prosecute.wav");
Schema.voices:AddDispatch("Quick", "Quick!", "npc/overwatch/radiovoice/quick.wav");
Schema.voices:AddDispatch("Recalibrate Scan", "Team, recalibrate socio scan.", "npc/overwatch/radiovoice/recalibratesocioscan.wav");
Schema.voices:AddDispatch("Recieving Conflicting Data", "We are recieving conflicting data.", "npc/overwatch/radiovoice/recievingconflictingdata.wav");
Schema.voices:AddDispatch("Reinforcment Code3", "Reinforment Team, Code 3.", "npc/overwatch/radiovoice/reinforcmentteamtcode3.wav");
Schema.voices:AddDispatch("Remaining Units Contain", "Remaining units contain.", "npc/overwatch/radiovoice/remainingunitscontain.wav");
Schema.voices:AddDispatch("Report On", "Local protection team units, report on.", "npc/overwatch/radiovoice/reporton.wav");
Schema.voices:AddDispatch("Report Please", "Report... please!", "npc/overwatch/radiovoice/reportplease.wav");
Schema.voices:AddDispatch("repurosedarea", "Repurosed Area.", "npc/overwatch/radiovoice/repurosedarea.wav");
Schema.voices:AddDispatch("Residential Block", "Residential Block.", "npc/overwatch/radiovoice/residentialblock.wav");
Schema.voices:AddDispatch("Respond", "Respond.", "npc/overwatch/radiovoice/respond.wav");
Schema.voices:AddDispatch("Restrict", "Restrict.", "npc/overwatch/radiovoice/restrict.wav");
Schema.voices:AddDispatch("Reward Notice", "Reward notice, protection team member your family cohesion.", "npc/overwatch/radiovoice/rewardnotice.wav");
Schema.voices:AddDispatch("404riot", "404 Riot.", "npc/overwatch/radiovoice/riot404.wav");
Schema.voices:AddDispatch("Roller", "Roller!", "npc/overwatch/radiovoice/roller.wav");
Schema.voices:AddDispatch("Search", "Search.", "npc/overwatch/radiovoice/search.wav");
Schema.voices:AddDispatch("Sector", "Sector!", "npc/overwatch/radiovoice/sector.wav");
Schema.voices:AddDispatch("Serve", "Serve!", "npc/overwatch/radiovoice/serve.wav");
Schema.voices:AddDispatch("7", "Seven.", "npc/overwatch/radiovoice/seven.wav");
Schema.voices:AddDispatch("6", "Six.", "npc/overwatch/radiovoice/six.wav");
Schema.voices:AddDispatch("Sociocide", "Sociocide.", "npc/overwatch/radiovoice/sociocide.wav");
Schema.voices:AddDispatch("Social Fracture Progress", "Social fracture in progress, respond.", "npc/overwatch/radiovoice/socialfractureinprogress.wav");
Schema.voices:AddDispatch("Socio Restored", "Socio abilization restored.", "npc/overwatch/radiovoice/socioabilizationrestored.wav");
Schema.voices:AddDispatch("Station Block", "Station Block!", "npc/overwatch/radiovoice/stationblock.wav");
Schema.voices:AddDispatch("Sterilize", "Sterilize.", "npc/overwatch/radiovoice/sterilize.wav");
Schema.voices:AddDispatch("Stick", "Stick!", "npc/overwatch/radiovoice/stick.wav");
Schema.voices:AddDispatch("Storm System", "Storm System.", "npc/overwatch/radiovoice/stormsystem.wav");
Schema.voices:AddDispatch("Subject", "Subject!", "npc/overwatch/radiovoice/subject.wav");
Schema.voices:AddDispatch("Suspend", "Suspend.", "npc/overwatch/radiovoice/suspend.wav");
Schema.voices:AddDispatch("Tap", "Tap.", "npc/overwatch/radiovoice/tap.wav");
Schema.voices:AddDispatch("Report Status", "Local Civil Protection team, report status.", "npc/overwatch/radiovoice/teamreportstatus.wav");
Schema.voices:AddDispatch("3", "Three", "npc/overwatch/radiovoice/three.wav");
Schema.voices:AddDispatch("Transit Block", "Transit Block.", "npc/overwatch/radiovoice/transitblock.wav");
Schema.voices:AddDispatch("2", "Two.", "npc/overwatch/radiovoice/two.wav");
Schema.voices:AddDispatch("Union", "Union!", "npc/overwatch/radiovoice/union.wav");
Schema.voices:AddDispatch("Unit Deserviced", "Unit Deserviced.", "npc/overwatch/radiovoice/unitdeserviced.wav");
Schema.voices:AddDispatch("Unit Down At", "Unit down at...", "npc/overwatch/radiovoice/unitdownat.wav");
Schema.voices:AddDispatch("UPI", "UPI.", "npc/overwatch/radiovoice/upi.wav");
Schema.voices:AddDispatch("Vice", "Vice!", "npc/overwatch/radiovoice/vice.wav");
Schema.voices:AddDispatch("Victor", "Victor!", "npc/overwatch/radiovoice/victor.wav");
Schema.voices:AddDispatch("Violation Of Civil Trust", "Violation of Civil trust.", "npc/overwatch/radiovoice/violationofciviltrust.wav");
Schema.voices:AddDispatch("Waste river", "Waste river.", "npc/overwatch/radiovoice/wasteriver.wav");
Schema.voices:AddDispatch("94 Weapon", "94 Weapon.", "npc/overwatch/radiovoice/weapon94.wav");
Schema.voices:AddDispatch("Work Force Intake", "Work force intake hub.", "npc/overwatch/radiovoice/workforceintake.wav");
Schema.voices:AddDispatch("Xray", "X-Ray!", "npc/overwatch/radiovoice/xray.wav");
Schema.voices:AddDispatch("Yellow", "Yellow!", "npc/overwatch/radiovoice/yellow.wav");
Schema.voices:AddDispatch("0", "Zero.", "npc/overwatch/radiovoice/zero.wav");
Schema.voices:AddDispatch("Zone", "Zone!", "npc/overwatch/radiovoice/zone.wav");
Schema.voices:AddDispatch("Judged Guilty", "You are Judged guilty, civil protection team.", "npc/overwatch/radiovoice/youarejudgedguilty.wav");
Schema.voices:AddDispatch("Unregistered Weapons", "Securety alert, un-registered weapons dedected, confsicating field and gate.", "npc/overwatch/radiovoice/fcitadel_confiscating.wav");
Schema.voices:AddDispatch("Confsication Failure", "Warning, counter resident singularity device dedected, confsication field failure.", "npc/overwatch/radiovoice/fcitadel_confiscationfailure.wav");
Schema.voices:AddDispatch("Illegal Device Dedected", "Securety alert, illegal counter resident singularity device dedected, DEPLOY, FAILURE, DEFECT.", "npc/overwatch/radiovoice/fcitadel_deploy.wav");
Schema.voices:AddDispatch("Transport Sequence", "Attention, Transport singularity INTERLOCK, SEQUENCE, ENGADGET.", "npc/overwatch/radiovoice/fcitadel_transportsequence.wav");
Schema.voices:AddDispatch("3m Singularity", "Warning, 3 minutes to singularity.", "npc/overwatch/radiovoice/fcitadel_3minutestosingularity.wav");
Schema.voices:AddDispatch("2m Singularity", "Warning, 2 minutes to singularity.", "npc/overwatch/radiovoice/fcitadel_2minutestosingularity.wav");
Schema.voices:AddDispatch("1m Singularity", "Warning, 1 minutes to singularity.", "npc/overwatch/radiovoice/fcitadel_1minutestosingularity.wav");
Schema.voices:AddDispatch("45s Singularity", "Priority Warning, 45 seconds to singularity.", "npc/overwatch/radiovoice/fcitadel_45sectosingularity.wav");
Schema.voices:AddDispatch("30s Singularity", "Priority Warning, 30 seconds to singularity.", "npc/overwatch/radiovoice/fcitadel_30sectosingularity.wav");
Schema.voices:AddDispatch("15s Singularity", "Priority Warning, 15 seconds to singularity.", "npc/overwatch/radiovoice/fcitadel_15sectosingularity.wav");
Schema.voices:AddDispatch("10s Singularity", "Priority Warning, 10 seconds to singularity.", "npc/overwatch/radiovoice/fcitadel_10sectosingularity.wav");
Schema.voices:AddDispatch("Nonstandart Exogen", "Alert, non-standart Exogen activity dedected. EXECUTE, CONTAINMENT, PROSECTURE and REPORT.", "npc/overwatch/radiovoice/fprison_nonstandartexogen.wav");
Schema.voices:AddDispatch("Freeman Located", "Incursion Warning, Airwatch reported Anti-Citizen: Freeman required, Zone: Nova-Prospekt. Ground units depriority exogens containment. Hope for overwide code.", "npc/overwatch/radiovoice/fprison_freemanlocated.wav");
Schema.voices:AddDispatch("Radio Random 1", "*Radio bad connection sound*", "ambient/levels/prison/radio_random1.wav");
Schema.voices:AddDispatch("Radio Random 2", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random2.wav");
Schema.voices:AddDispatch("Radio Random 3", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random3.wav");
Schema.voices:AddDispatch("Radio Random 4", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random4.wav");
Schema.voices:AddDispatch("Radio Random 5", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random5.wav");
Schema.voices:AddDispatch("Radio Random 6", "*Radio bad connection sounds*", "ambient/levels/prison/radio_random6.wav");
Schema.voices:AddDispatch("Radio Random 7", "*Radio sounds*", "ambient/levels/prison/radio_random7.wav");
Schema.voices:AddDispatch("Radio Random 8", "*Radio sounds*", "ambient/levels/prison/radio_random8.wav");
Schema.voices:AddDispatch("Radio Random 9", "*Radio sounds*", "ambient/levels/prison/radio_random9.wav");
Schema.voices:AddDispatch("Radio Random 10", "*Radio sounds*", "ambient/levels/prison/radio_random10.wav");
Schema.voices:AddDispatch("Radio Random 11", "*Radio sounds*", "ambient/levels/prison/radio_random11.wav");
Schema.voices:AddDispatch("Radio Random 12", "*Radio sounds*", "ambient/levels/prison/radio_random12.wav");
Schema.voices:AddDispatch("Radio Random 13", "*Radio sounds*", "ambient/levels/prison/radio_random13.wav");
Schema.voices:AddDispatch("Radio Random 14", "*Radio sounds*", "ambient/levels/prison/radio_random14.wav");
Schema.voices:AddDispatch("Radio Random 15", "*Radio sounds*", "ambient/levels/prison/radio_random15.wav");

if (CLIENT) then
	table.sort(Schema.voices.stored.dispatchVoices, function(a, b) return a.command < b.command; end);

	for k, v in pairs(Schema.voices.stored.dispatchVoices) do
		Clockwork.directory:AddCode("Dispatch", [[
			<div class="auraInfoTitle">]]..string.upper(v.command)..[[</div>
			<div class="auraInfoText">]]..v.phrase..[[</div>
		]], true);
	end;
end;

-- End. Delete everything from the most recent comment to remove dispatch voices.
